import { Router } from 'express';
import { authenticate } from '../../shared/middleware/auth.js';
import * as controller from './busqueda.controller.js';
const router = Router();
router.get('/', controller.buscar);
router.get('/mapa', controller.buscarEnMapa);
router.get('/favoritos', authenticate, controller.getFavoritos);
router.post('/favoritos/:propiedadId', authenticate, controller.agregarFavorito);
router.delete('/favoritos/:propiedadId', authenticate, controller.eliminarFavorito);
router.get('/alertas', authenticate, controller.getAlertas);
router.post('/alertas', authenticate, controller.crearAlerta);
router.delete('/alertas/:id', authenticate, controller.eliminarAlerta);
export default router;
